spring:
  application:
    name: wise-task-graph
  data:
    mongodb:
      host: localhost
      port: 27017
      database: wise_task_graph

server:
  port: 8080

grpc:
  port: 6565

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'